### ISSUE TITLE
Logo + Brand Color

### ISSUE THREAD

**Issue by bookchin** [orcproject/horde#2]
Let's add the ORC logo and use the purple `#800080`

**Comment by jhonghee** [comment]
Theme has been applied and logo has been added.

Anyone who wants to modify the theme, here's the steps.

1) you need to override default variables of antd. You can find the default variable here, https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

2) Put your overriding variables for the defaults in /src/theme.less

3) yarn run build-theme or npm run build-theme
